#!/bin/sh

# A simple script that queries the shelter verify endpoint to
# authenticate an account. The exit code tells about success or
# failure.
#
# This works only, if the default `add-verify-route' is enabled.

if [ -z "$CURL_BIN" ]; then
    CURL_BIN=curl
fi

COMMAND="$CURL_BIN -s -D /dev/stdout --data-urlencode login=$2 --data-urlencode password=$3 "
if [ -n "$4" ]; then
    COMMAND="$COMMAND --data-urlencode app=$4 "
fi
$COMMAND "http://$1/api/verify/form" | head -n1 | grep "200 OK"
